const types = {
  GET_HIGH_VALUE_ITEMS: "GET_HIGH_VALUE_ITEMS",
  GET_HIGH_VALUE_ITEMS__BY_USER: "GET_HIGH_VALUE_ITEMS__BY_USER",
  LOAD_HIGH_VALUE_ITEMS_IN_PROGRESS: "LOAD_HIGH_VALUE_ITEMS_IN_PROGRESS",
  LOAD_HIGH_VALUE_ITEMS_SUCCESS: "LOAD_HIGH_VALUE_ITEMS_SUCCESS",
  LOAD_HIGH_VALUE_ITEMS_FAILURE: "LOAD_HIGH_VALUE_ITEMS_FAILURE",
  CREATE_HIGH_VALUE_ITEM: "CREATE_HIGH_VALUE_ITEM",
  REMOVE_HIGH_VALUE_ITEM: "REMOVE_HIGH_VALUE_ITEM",
  REQUEST_HIGH_VALUE_ITEMS: "REQUEST_HIGH_VALUE_ITEMS",
  RECEIVE_HIGH_VALUE_ITEMS: "RECEIVE_HIGH_VALUE_ITEMS",
};

export default types;
