const types = {
  LOAD_HIGH_VALUE_ITEMS_IN_PROGRESS: "LOAD_HIGH_VALUE_ITEMS_IN_PROGRESS",
  LOAD_HIGH_VALUE_ITEMS_SUCCESS: "LOAD_HIGH_VALUE_ITEMS_SUCCESS",
  LOAD_HIGH_VALUE_ITEMS_PER_CATEGORY_SUCCESS:
    "LOAD_HIGH_VALUE_ITEMS_PER_CATEGORY_SUCCESS",
  LOAD_HIGH_VALUE_ITEMS_FAILURE: "LOAD_HIGH_VALUE_ITEMS_FAILURE",
  CREATE_HIGH_VALUE_ITEM: "CREATE_HIGH_VALUE_ITEM",
  REMOVE_HIGH_VALUE_ITEM: "REMOVE_HIGH_VALUE_ITEM",
};

export default types;
